import pandas as pd
import plotly.express as px



def display_scatter_plot_rot(y_axis: str) -> None:
    
    #Read the CSV generated by C++
    if(y_axis.lower() == "x"): 
        df = pd.read_csv("logging/dataRotX.csv") 
    else:
        df = pd.read_csv("logging/dataRotY.csv")

    #Create an interactive scatter plot
    fig = px.scatter(df, x="t", y=f"rot{y_axis.upper()}", title=f"Simulation Data: t(s) vs rot{y_axis.upper()}(deg)")

    #Add lines connecting the points 
    fig.update_traces(mode='markers+lines')




    #Display the plot
    fig.show()


def display_scatter_plot_return() -> None:
    

    df = pd.read_csv("logging/averageReturnE-1000.csv") 

    #Create an interactive scatter plot
    fig = px.scatter(df, x="episodes", y="averageReturn", title=f"Training Data: episodes(x10^3) vs averageReturn")

    #Add lines connecting the points 
    fig.update_traces(mode="lines", line=dict(color="green"), marker=dict(color="green"))




    #Display the plot
    fig.show()

def main() -> None:

    data_to_display: str = input("Display return or rotations(g/r): ")

    if(data_to_display == "g"):
        display_scatter_plot_return()
    else:
        axis_display: str = input("Enter the rotations you would like to view(x/y): ")

        display_scatter_plot_rot(axis_display) 

if __name__ == "__main__":
    main() 